## Project Requirements
Analyze the impact of age on athlete performance by generating a synthetic dataset, exploring its structure, performing statistical analysis on the relationship between 'Age' and a 'Performance Metric', visualizing the findings, and summarizing the overall insights.

## Generate Synthetic Dataset

Create a synthetic dataset that simulates athlete performance across different age groups in professional sports.

In [1]:
import numpy as np
import pandas as pd
print("Libraries numpy and pandas imported.")

Libraries numpy and pandas imported.


In [2]:
num_athletes = 1000
ages = np.random.randint(18, 45, num_athletes) # Ages between 18 and 44

# Define a performance metric that peaks around age 30 and declines thereafter
peak_age = 30
max_performance = 100
performance_noise = np.random.normal(0, 10, num_athletes) # Add random noise

# A quadratic relationship to simulate peak performance
performance_metric = -0.5 * (ages - peak_age)**2 + max_performance + performance_noise

# Ensure performance is not negative (e.g., minimum performance of 10)
performance_metric[performance_metric < 10] = 10

data = {'Age': ages, 'Performance Metric': performance_metric}
df = pd.DataFrame(data)

print("Synthetic dataset 'df' created with 'Age' and 'Performance Metric' columns.")
print(df.head())

Synthetic dataset 'df' created with 'Age' and 'Performance Metric' columns.
   Age  Performance Metric
0   30           96.594363
1   29           81.347157
2   29          110.336539
3   44           10.000000
4   18           28.858191


## Explore Dataset

Load the generated dataset and perform initial exploratory data analysis to understand its structure, distributions, and basic statistics for 'Age' and 'Performance Metric'.


In [3]:
print("1. DataFrame shape:")
print(df.shape)

print("\n2. DataFrame info:")
df.info()

print("\n3. Descriptive statistics:")
print(df.describe())

print("\n4. Missing values:")
print(df.isnull().sum())

print("\n5. First 5 rows of the DataFrame:")
print(df.head())

1. DataFrame shape:
(1000, 2)

2. DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 1000 non-null   int64  
 1   Performance Metric  1000 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 15.8 KB

3. Descriptive statistics:
               Age  Performance Metric
count  1000.000000         1000.000000
mean     31.252000           70.183124
std       7.722832           29.264729
min      18.000000           10.000000
25%      25.000000           47.851780
50%      31.000000           77.033110
75%      38.000000           93.130308
max      44.000000          132.306881

4. Missing values:
Age                   0
Performance Metric    0
dtype: int64

5. First 5 rows of the DataFrame:
   Age  Performance Metric
0   30           96.594363
1   29           81.347157
2   29          110.33

## Analyze Age Impact

Perform statistical analysis to investigate the relationship between 'Age' and the 'Performance Metric'.

In [4]:
print("1. Pearson correlation coefficient between Age and Performance Metric:")
correlation = df['Age'].corr(df['Performance Metric'])
print(f"Pearson Correlation: {correlation:.4f}")

print("\n2. Mean Performance Metric by Age Group:")
performance_by_age = df.groupby('Age')['Performance Metric'].mean().reset_index()

print("\n3. First few rows of mean performance by age:")
print(performance_by_age.head())

1. Pearson correlation coefficient between Age and Performance Metric:
Pearson Correlation: -0.2848

2. Mean Performance Metric by Age Group:

3. First few rows of mean performance by age:
   Age  Performance Metric
0   18           28.467698
1   19           39.933993
2   20           51.606121
3   21           61.447487
4   22           69.357746


The statistical analysis part of the subtask has been completed. Now, I will visualize the relationship between 'Age' and 'Performance Metric' using a scatter plot and a line plot of the mean performance by age to visually represent the findings.



In [5]:
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries matplotlib.pyplot and seaborn imported.")

plt.figure(figsize=(12, 6))
sns.scatterplot(x='Age', y='Performance Metric', data=df, alpha=0.6, label='Individual Performance')
sns.lineplot(x='Age', y='Performance Metric', data=performance_by_age, color='red', linewidth=2, label='Mean Performance by Age')
plt.title('Athlete Performance vs. Age')
plt.xlabel('Age')
plt.ylabel('Performance Metric')
plt.grid(True)
plt.legend()
plt.show()

print("Scatter plot and line plot showing performance vs. age generated.")

Libraries matplotlib.pyplot and seaborn imported.


Scatter plot and line plot showing performance vs. age generated.


### Data Analysis Key Findings
*   A synthetic dataset was successfully created, comprising 1000 athletes with ages ranging from 18 to 44 years. The 'Performance Metric' was designed to peak around age 30 and decline thereafter.
*   The dataset contained 1000 rows and 2 columns ('Age' and 'Performance Metric'), with no missing values.
*   Descriptive statistics showed an average athlete age of approximately 31.25 years and a wide range in performance metric values from 10.0 to 132.31, with an average of 70.18.
*   The Pearson correlation coefficient between 'Age' and 'Performance Metric' was calculated as -0.2848, indicating a weak negative linear relationship across the entire age range.
*   Analyzing mean performance by age group revealed a non-linear trend:
    *   Performance initially improved, for example, from an average of 28.47 at age 18 to 69.36 at age 22.
    *   A peak performance was observed around the age range of 29-31 years.
    *   Following this peak, there was a consistent and noticeable decline in performance as athletes aged into their mid-30s and beyond.
*   Visualizations (scatter plot and mean performance line plot) confirmed this parabolic-like trajectory, showing an initial rise, a peak, and then a gradual descent in average performance with increasing age.